#import = [
#  "~/.config/alacritty/themes/gruvbox-dark.toml"
#]

[window.padding]
x = 15
y = 15

[colors.primary]
background = '#141414'
foreground = '#a7a7a7'
#dim_foreground = "#CDD6F4"
#bright_foreground = "#CDD6F4"


[colors.cursor]
text = "#1E1E2E"
cursor = "#a7a7a7"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[font]
size = 10

[font.normal]
family = "JetBrainsMonoNLNerdFontMono"
style = "Bold"

[window]
opacity = 1
